apiVersion: apps/v1
kind: Deployment
metadata:
  name: drift
  labels:
    app: drift
spec:
  replicas: 3
  selector:
    matchLabels:
      app: drift
  template:
    metadata:
      labels:
        app: drift
    spec:
      serviceAccountName: drift
      containers:
        - name: drift
          image: registry.prod.bbdops.com/common/drift:v0.0.4
          command:
            - drift
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "drift"
