apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: drift-ingress
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            backend:
              serviceName: drift-api
              servicePort: 8000
          - path: /
            backend:
              serviceName: drift-vue-service
              servicePort: 80